name: go.mod Tidy Checker

on:
  push:
    branches:
      - master
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

jobs:
  main:
    name: Ensure go.mods are tidied
    runs-on: gnolang-self-runner-medium
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check go.mod files are up to date
        working-directory: ./examples
        run: |
          make tidy VERIFY_MOD_SUMS=true
